[2024-07-13 16:24:02 +0000] [7729] [INFO] Starting gunicorn 22.0.0
[2024-07-13 16:24:02 +0000] [7729] [ERROR] Connection in use: ('0.0.0.0', 8003)
[2024-07-13 16:24:02 +0000] [7729] [ERROR] Retrying in 1 second.
[2024-07-13 16:24:03 +0000] [7729] [ERROR] Connection in use: ('0.0.0.0', 8003)
[2024-07-13 16:24:03 +0000] [7729] [ERROR] Retrying in 1 second.
[2024-07-13 16:24:04 +0000] [7729] [ERROR] Connection in use: ('0.0.0.0', 8003)
[2024-07-13 16:24:04 +0000] [7729] [ERROR] Retrying in 1 second.
[2024-07-13 16:24:05 +0000] [7729] [ERROR] Connection in use: ('0.0.0.0', 8003)
[2024-07-13 16:24:05 +0000] [7729] [ERROR] Retrying in 1 second.
[2024-07-13 16:24:06 +0000] [7729] [ERROR] Connection in use: ('0.0.0.0', 8003)
[2024-07-13 16:24:06 +0000] [7729] [ERROR] Retrying in 1 second.
[2024-07-13 16:24:07 +0000] [7729] [ERROR] Can't connect to ('0.0.0.0', 8003)
[2024-07-13 16:24:39 +0000] [7990] [INFO] Starting gunicorn 22.0.0
[2024-07-13 16:24:39 +0000] [7990] [INFO] Listening at: http://0.0.0.0:8000 (7990)
[2024-07-13 16:24:39 +0000] [7990] [INFO] Using worker: sync
[2024-07-13 16:24:39 +0000] [7994] [INFO] Booting worker with pid: 7994
[2024-07-13 16:27:03 +0000] [8719] [INFO] Starting gunicorn 22.0.0
[2024-07-13 16:27:03 +0000] [8719] [INFO] Listening at: http://0.0.0.0:8005 (8719)
[2024-07-13 16:27:03 +0000] [8719] [INFO] Using worker: sync
[2024-07-13 16:27:03 +0000] [8723] [INFO] Booting worker with pid: 8723
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
 
 -------------- celery@ip-172-31-91-236 v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-6.8.0-1009-aws-x86_64-with-glibc2.39 2024-07-13 16:29:39
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks_app:0x7cff9e385f10
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . core.tasks.send_email_task
  . messaging_system.celery.debug_task

[2024-07-13 16:29:39,873: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-13 16:29:39,900: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-07-13 16:29:39,903: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-13 16:29:39,908: INFO/MainProcess] mingle: searching for neighbors
[2024-07-13 16:29:40,934: INFO/MainProcess] mingle: all alone
[2024-07-13 16:29:40,950: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/kombu/pidbox.py:72: UserWarning: A node named celery@ip-172-31-91-236 is already using this process mailbox!

Maybe you forgot to shutdown the other node or did not do so properly?
Or if you meant to start multiple nodes on the same host please make sure
you give each node a unique node name!

  warnings.warn(W_PIDBOX_IN_USE.format(node=self))

[2024-07-13 16:29:40,952: INFO/MainProcess] celery@ip-172-31-91-236 ready.
[2024-07-13 16:35:11,680: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 746, in start
    c.loop(*c.loop_args())
  File "/home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/loops.py", line 88, in asynloop
    raise heartbeat_error[0]
  File "/home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/loops.py", line 40, in tick
    connection.heartbeat_check(rate)
  File "/home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/kombu/connection.py", line 328, in heartbeat_check
    return self.transport.heartbeat_check(self.connection, rate=rate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/kombu/transport/pyamqp.py", line 222, in heartbeat_check
    return connection.heartbeat_tick(rate=rate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/amqp/connection.py", line 776, in heartbeat_tick
    raise ConnectionForced('Too many heartbeats missed')
amqp.exceptions.ConnectionForced: Too many heartbeats missed
[2024-07-13 16:35:13,697: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:391: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2024-07-13 16:35:16,608: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-13 16:35:23,671: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 2.00 seconds... (1/100)

[2024-07-13 16:35:31,924: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 4.00 seconds... (2/100)

[2024-07-13 16:35:41,902: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 6.00 seconds... (3/100)

[2024-07-13 16:35:52,818: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 8.00 seconds... (4/100)

[2024-07-13 16:36:06,247: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 10.00 seconds... (5/100)

[2024-07-13 16:36:21,055: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 12.00 seconds... (6/100)

[2024-07-13 16:38:29 +0000] [7990] [CRITICAL] WORKER TIMEOUT (pid:7994)
[2024-07-13 16:38:29 +0000] [8719] [CRITICAL] WORKER TIMEOUT (pid:8723)
[2024-07-13 16:39:27,449: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 14.00 seconds... (7/100)

[2024-07-13 16:39:46 +0000] [7990] [ERROR] Worker (pid:7994) was sent SIGKILL! Perhaps out of memory?
[2024-07-13 16:39:46 +0000] [8719] [ERROR] Worker (pid:8723) was sent SIGKILL! Perhaps out of memory?
[2024-07-13 16:39:46 +0000] [10544] [INFO] Booting worker with pid: 10544
[2024-07-13 16:39:46 +0000] [10545] [INFO] Booting worker with pid: 10545
 
 -------------- worker1@ip-172-31-91-236 v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-6.8.0-1009-aws-x86_64-with-glibc2.39 2024-07-13 16:39:47
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks_app:0x7283c5489df0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . core.tasks.send_email_task
  . messaging_system.celery.debug_task

[2024-07-13 16:39:47,906: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-13 16:39:48,056: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-07-13 16:39:48,072: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-13 16:39:48,094: INFO/MainProcess] mingle: searching for neighbors
[2024-07-13 16:39:49,193: INFO/MainProcess] mingle: all alone
[2024-07-13 16:39:49,262: INFO/MainProcess] worker1@ip-172-31-91-236 ready.
[2024-07-13 16:40:07,454: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 16.00 seconds... (8/100)

[2024-07-13 16:40:40,417: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 18.00 seconds... (9/100)

[2024-07-13 16:41:15,145: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 20.00 seconds... (10/100)

[2024-07-13 16:41:47,406: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: timed out.
Trying again in 22.00 seconds... (11/100)

[2024-07-13 16:50:10 +0000] [1359] [INFO] Starting gunicorn 22.0.0
[2024-07-13 16:50:10 +0000] [1359] [INFO] Listening at: http://0.0.0.0:8005 (1359)
[2024-07-13 16:50:10 +0000] [1359] [INFO] Using worker: sync
[2024-07-13 16:50:10 +0000] [1360] [INFO] Booting worker with pid: 1360
 
 -------------- celery@ip-172-31-91-236 v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-6.8.0-1009-aws-x86_64-with-glibc2.39 2024-07-13 16:50:39
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks_app:0x774549e8a000
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . core.tasks.send_email_task
  . messaging_system.celery.debug_task

[2024-07-13 16:50:40,015: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-13 16:50:40,023: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-07-13 16:50:40,024: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-13 16:50:40,027: INFO/MainProcess] mingle: searching for neighbors
[2024-07-13 16:50:41,044: INFO/MainProcess] mingle: all alone
[2024-07-13 16:50:41,059: INFO/MainProcess] celery@ip-172-31-91-236 ready.
http - start an HTTP tunnel

USAGE:
  ngrok http [address:port | port] [flags]

AUTHOR:
  ngrok - <support@ngrok.com>

COMMANDS: 
  config          update or migrate ngrok's configuration file
  http            start an HTTP tunnel
  tcp             start a TCP tunnel
  tunnel          start a tunnel for use with a tunnel-group backend

EXAMPLES: 
  ngrok http 80                                                 # secure public URL for port 80 web server
  ngrok http --domain baz.ngrok.dev 8080                        # port 8080 available at baz.ngrok.dev
  ngrok tcp 22                                                  # tunnel arbitrary TCP traffic to port 22
  ngrok http 80 --oauth=google --oauth-allow-email=foo@foo.com  # secure your app with oauth

Paid Features: 
  ngrok http 80 --domain mydomain.com                           # run ngrok with your own custom domain
  ngrok http 80 --allow-cidr 2600:8c00::a03c:91ee:fe69:9695/32  # run ngrok with IP policy restrictions
  Upgrade your account at https://dashboard.ngrok.com/billing/subscription to access paid features

Upgrade your account at https://dashboard.ngrok.com/billing/subscription to access paid features

Flags:
  -h, --help      help for ngrok

Use "ngrok [command] --help" for more information about a command.

ERROR:  authentication failed: Your account is limited to 1 simultaneous ngrok agent sessions.
ERROR:  You can run multiple tunnels on a single agent session using a configuration file.
ERROR:  To learn more, see https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/config/
ERROR:  You can view your current agent sessions in the dashboard:
ERROR:  https://dashboard.ngrok.com/tunnels/agents
ERROR:  
ERROR:  ERR_NGROK_108
ERROR:  https://ngrok.com/docs/errors/err_ngrok_108
ERROR:  
http - start an HTTP tunnel

USAGE:
  ngrok http [address:port | port] [flags]

AUTHOR:
  ngrok - <support@ngrok.com>

COMMANDS: 
  config          update or migrate ngrok's configuration file
  http            start an HTTP tunnel
  tcp             start a TCP tunnel
  tunnel          start a tunnel for use with a tunnel-group backend

EXAMPLES: 
  ngrok http 80                                                 # secure public URL for port 80 web server
  ngrok http --domain baz.ngrok.dev 8080                        # port 8080 available at baz.ngrok.dev
  ngrok tcp 22                                                  # tunnel arbitrary TCP traffic to port 22
  ngrok http 80 --oauth=google --oauth-allow-email=foo@foo.com  # secure your app with oauth

Paid Features: 
  ngrok http 80 --domain mydomain.com                           # run ngrok with your own custom domain
  ngrok http 80 --allow-cidr 2600:8c00::a03c:91ee:fe69:9695/32  # run ngrok with IP policy restrictions
  Upgrade your account at https://dashboard.ngrok.com/billing/subscription to access paid features

Upgrade your account at https://dashboard.ngrok.com/billing/subscription to access paid features

Flags:
  -h, --help      help for ngrok

Use "ngrok [command] --help" for more information about a command.

ERROR:  authentication failed: Your account is limited to 1 simultaneous ngrok agent sessions.
ERROR:  You can run multiple tunnels on a single agent session using a configuration file.
ERROR:  To learn more, see https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/config/
ERROR:  You can view your current agent sessions in the dashboard:
ERROR:  https://dashboard.ngrok.com/tunnels/agents
ERROR:  
ERROR:  ERR_NGROK_108
ERROR:  https://ngrok.com/docs/errors/err_ngrok_108
ERROR:  
Not Found: /
Not Found: /favicon.ico
[2024-07-13 17:05:16 +0000] [1359] [INFO] Handling signal: hup
[2024-07-13 17:05:16 +0000] [1359] [INFO] Hang up: Master

Restarting celery worker (/home/ubuntu/django-rabbitmq-celery-smtp/envhng3/bin/celery -A messaging_system worker -l info)
[2024-07-13 17:05:16 +0000] [1359] [ERROR] Worker (pid:1360) was sent SIGHUP!
[2024-07-13 17:05:16 +0000] [3328] [INFO] Booting worker with pid: 3328
 
 -------------- celery@ip-172-31-91-236 v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-6.8.0-1009-aws-x86_64-with-glibc2.39 2024-07-13 17:05:18
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks_app:0x77993c189e80
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . core.tasks.send_email_task
  . messaging_system.celery.debug_task

[2024-07-13 17:05:18,188: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-13 17:05:18,202: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-07-13 17:05:18,204: WARNING/MainProcess] /home/ubuntu/django-rabbitmq-celery-smtp/envhng3/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-13 17:05:18,210: INFO/MainProcess] mingle: searching for neighbors
[2024-07-13 17:05:19,234: INFO/MainProcess] mingle: all alone
[2024-07-13 17:05:19,250: INFO/MainProcess] celery@ip-172-31-91-236 ready.
Not Found: /
Not Found: /
[2024-07-13 17:08:14 +0000] [3328] [INFO] Worker exiting (pid: 3328)
[2024-07-13 17:08:14 +0000] [1359] [INFO] Handling signal: term
[2024-07-13 17:08:14 +0000] [1359] [ERROR] Worker (pid:3328) was sent SIGTERM!
[2024-07-13 17:08:14 +0000] [1359] [INFO] Shutting down: Master
[2024-07-13 17:08:50 +0000] [3769] [INFO] Starting gunicorn 22.0.0
[2024-07-13 17:08:50 +0000] [3769] [INFO] Listening at: http://0.0.0.0:8005 (3769)
[2024-07-13 17:08:50 +0000] [3769] [INFO] Using worker: sync
[2024-07-13 17:08:50 +0000] [3773] [INFO] Booting worker with pid: 3773
[2024-07-13 17:08:58 +0000] [3891] [INFO] Starting gunicorn 22.0.0
[2024-07-13 17:08:58 +0000] [3891] [ERROR] Connection in use: ('0.0.0.0', 8005)
[2024-07-13 17:08:58 +0000] [3891] [ERROR] Retrying in 1 second.
[2024-07-13 17:08:59 +0000] [3891] [ERROR] Connection in use: ('0.0.0.0', 8005)
[2024-07-13 17:08:59 +0000] [3891] [ERROR] Retrying in 1 second.
[2024-07-13 17:09:00 +0000] [3891] [ERROR] Connection in use: ('0.0.0.0', 8005)
[2024-07-13 17:09:00 +0000] [3891] [ERROR] Retrying in 1 second.
[2024-07-13 17:09:01 +0000] [3891] [ERROR] Connection in use: ('0.0.0.0', 8005)
[2024-07-13 17:09:01 +0000] [3891] [ERROR] Retrying in 1 second.
[2024-07-13 17:09:02 +0000] [3891] [ERROR] Connection in use: ('0.0.0.0', 8005)
[2024-07-13 17:09:02 +0000] [3891] [ERROR] Retrying in 1 second.
[2024-07-13 17:09:03 +0000] [3891] [ERROR] Can't connect to ('0.0.0.0', 8005)
[2024-07-13 17:09:31,910: INFO/MainProcess] Task core.tasks.send_email_task[04fb91f3-09e8-490b-8c7b-efacdfc19f7b] received
[2024-07-13 17:09:32,755: INFO/ForkPoolWorker-1] Task core.tasks.send_email_task[04fb91f3-09e8-490b-8c7b-efacdfc19f7b] succeeded in 0.8431565440000668s: None
[2024-07-13 17:11:00,409: INFO/MainProcess] Task core.tasks.send_email_task[7a09fdfc-a820-4b85-8921-4327cc759c85] received
[2024-07-13 17:11:01,214: INFO/ForkPoolWorker-1] Task core.tasks.send_email_task[7a09fdfc-a820-4b85-8921-4327cc759c85] succeeded in 0.8049058390001846s: None
[2024-07-13 17:11:29 +0000] [3769] [INFO] Handling signal: hup
[2024-07-13 17:11:29 +0000] [3769] [INFO] Hang up: Master
[2024-07-13 17:11:29 +0000] [3769] [ERROR] Worker (pid:3773) was sent SIGHUP!
[2024-07-13 17:11:29 +0000] [4165] [INFO] Booting worker with pid: 4165
[2024-07-13 17:11:32,491: INFO/MainProcess] Task core.tasks.send_email_task[3ed72025-32e0-4711-a23d-880455c033c5] received
[2024-07-13 17:11:33,311: INFO/ForkPoolWorker-1] Task core.tasks.send_email_task[3ed72025-32e0-4711-a23d-880455c033c5] succeeded in 0.8189660390000881s: None
[2024-07-13 17:11:45,077: INFO/MainProcess] Task core.tasks.send_email_task[abf69f79-32be-493b-aff3-117913e4c59b] received
[2024-07-13 17:11:45,897: INFO/ForkPoolWorker-1] Task core.tasks.send_email_task[abf69f79-32be-493b-aff3-117913e4c59b] succeeded in 0.8185965520001446s: None
